@startuml
autonumber
actor       Test       as test
participant Service as svc
participant Toxiproxy as proxy
queue NATS as nats

activate test
    test -> svc: Launch service with decreased\nmax reconnect property for test
    test -> proxy: Disable NATS connection
    activate proxy
        proxy -> test: OK
    deactivate proxy

    test -> svc: POST /telemetry
    activate svc
        svc x--> proxy: Publish NATS message
        svc -> test: 200 OK
    deactivate svc

    test -> test: Wait 5 seconds
    ...
    test -> test: Verify that no NATS messages were received
    test -> proxy: Enable NATS connection
    activate proxy
        proxy -> test: OK
    deactivate proxy
    
    test -> svc: POST /telemetry
    activate svc
        svc -> test: 500 Internal Server Error
    deactivate svc

    test -> svc: Restart service

    test -> svc: POST /telemetry
    activate svc
        svc --> proxy: Publish NATS message
        proxy --> nats: Publish NATS message
        svc -> test: 200 OK
    deactivate svc

    test <-- nats: NATS message
deactivate test

@enduml